CREATE TABLE `ADK_APPLICANT` (
  `ADK_APPLICANT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADK_APPLICANT_USERNAME` varchar(45) DEFAULT NULL,
  `ADK_APPLICANT_NAME` varchar(40) DEFAULT NULL,
  `ADK_APPLICANT_EMAIL` varchar(50) DEFAULT NULL,
  `ADK_APPLICANT_PHONE` varchar(11) DEFAULT NULL,
  `ADK_APPLICANT_AGE` int(3) DEFAULT NULL,
  `ADK_APPLICANT_SEX` varchar(1) DEFAULT NULL,
  `ADK_APPLICANT_ADDRESS1` varchar(40) DEFAULT NULL,
  `ADK_APPLICANT_ADDRESS2` varchar(40) DEFAULT NULL,
  `ADK_APPLICANT_CITY` varchar(40) DEFAULT NULL,
  `ADK_APPLICANT_STATE` varchar(2) DEFAULT NULL,
  `ADK_APPLICANT_ZIP` varchar(9) DEFAULT NULL,
  `ADK_APPLICANT_COUNTRY` varchar(40) DEFAULT NULL,
  `ADK_APPLICANT_PERSONALINFO` varchar(1024) DEFAULT NULL,
  `ADK_APPLICANT_REQ_CORR` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`ADK_APPLICANT_ID`),
  UNIQUE KEY `ADK_APPLICANT_ID_UNIQUE` (`ADK_APPLICANT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=94 DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_CHANGELOG` (
  `ADK_CHANGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADK_CHANGE_TITLE` varchar(40) NOT NULL,
  `ADK_CHANGE_DESC` varchar(1024) DEFAULT NULL,
  `ADK_CHANGE_DTE` datetime NOT NULL,
  `ADK_CHANGE_PRIORITY` int(1) NOT NULL,
  `ADK_CHANGE_DONE` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ADK_CHANGE_ID`),
  UNIQUE KEY `ADK_CHANGE_ID_UNIQUE` (`ADK_CHANGE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_CORRESPONDENT` (
  `ADK_USER_ID` int(11) NOT NULL,
  `ADK_CORR_PHOTO_ID` int(11) DEFAULT NULL,
  `ADK_CORR_PERSONALINFO` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`ADK_USER_ID`),
  UNIQUE KEY `ADK_USER_ID_UNIQUE` (`ADK_USER_ID`),
  CONSTRAINT `ADK_CORR_USER_ID` FOREIGN KEY (`ADK_USER_ID`) REFERENCES `ADK_USER` (`ADK_USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_FILE` (
  `ADK_FILE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADK_FILE_NAME` varchar(60) NOT NULL,
  `ADK_FILE_SAVENAME` varchar(40) NOT NULL,
  `ADK_FILE_DESC` varchar(1024) DEFAULT NULL,
  `ADK_FILE_SIZE` int(11) NOT NULL,
  `ADK_FILE_TYPE` varchar(40) NOT NULL,
  PRIMARY KEY (`ADK_FILE_ID`),
  UNIQUE KEY `ADK_FILE_ID_UNIQUE` (`ADK_FILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=142 DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_HIKE` (
  `ADK_HIKE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADK_USER_ID` int(11) NOT NULL,
  `ADK_HIKE_NOTES` varchar(4096) DEFAULT NULL,
  `ADK_HIKE_DTE` datetime NOT NULL,
  PRIMARY KEY (`ADK_HIKE_ID`),
  UNIQUE KEY `ADK_HIKE_ID_UNIQUE` (`ADK_HIKE_ID`),
  KEY `ADK_USER_ID_idx` (`ADK_USER_ID`),
  CONSTRAINT `_ADK_USER_ID` FOREIGN KEY (`ADK_USER_ID`) REFERENCES `ADK_USER` (`ADK_USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_HIKE_FILE_JCT` (
  `ADK_HIKE_ID` int(11) NOT NULL,
  `ADK_FILE_ID` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_HIKE_PEAK_JCT` (
  `ADK_HIKE_ID` int(11) NOT NULL,
  `ADK_PEAK_ID` int(11) NOT NULL,
  KEY `ADK_PEAK_ID_idx` (`ADK_PEAK_ID`),
  KEY `ADK_HIKE_ID_idx` (`ADK_HIKE_ID`),
  CONSTRAINT `ADK_PEAK_ID_` FOREIGN KEY (`ADK_PEAK_ID`) REFERENCES `ADK_PEAK` (`ADK_PEAK_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ADK_HIKE_ID` FOREIGN KEY (`ADK_HIKE_ID`) REFERENCES `ADK_HIKE` (`ADK_HIKE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_HIKER` (
  `ADK_USER_ID` int(11) NOT NULL,
  `ADK_HIKER_CORR_ID` int(11) NOT NULL,
  `ADK_HIKER_PHONE` varchar(14) DEFAULT NULL,
  `ADK_HIKER_AGE` int(3) DEFAULT NULL,
  `ADK_HIKER_SEX` varchar(1) DEFAULT NULL,
  `ADK_HIKER_ADDRESS1` varchar(40) NOT NULL,
  `ADK_HIKER_ADDRESS2` varchar(40) DEFAULT NULL,
  `ADK_HIKER_CITY` varchar(40) NOT NULL,
  `ADK_HIKER_STATE` varchar(2) NOT NULL,
  `ADK_HIKER_ZIP` varchar(10) NOT NULL,
  `ADK_HIKER_COUNTRY` varchar(40) NOT NULL,
  `ADK_HIKER_PERSONALINFO` varchar(1024) NOT NULL,
  `ADK_HIKER_FIRSTPEAK_ID` int(11) NOT NULL,
  `ADK_HIKER_FIRSTPEAK_DTE` datetime NOT NULL,
  `ADK_HIKER_LASTPEAK_ID` int(11) DEFAULT NULL,
  `ADK_HIKER_LASTPEAK_DTE` datetime DEFAULT NULL,
  PRIMARY KEY (`ADK_USER_ID`),
  UNIQUE KEY `ADK_USER_ID_UNIQUE` (`ADK_USER_ID`),
  KEY `ADK_FIRSTPEAK_ID_idx` (`ADK_HIKER_FIRSTPEAK_ID`),
  KEY `ADK_LASTPEAK_ID_idx` (`ADK_HIKER_LASTPEAK_ID`),
  CONSTRAINT `ADK_LASTPEAK_ID` FOREIGN KEY (`ADK_HIKER_LASTPEAK_ID`) REFERENCES `ADK_PEAK` (`ADK_PEAK_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ADK_USER_ID` FOREIGN KEY (`ADK_USER_ID`) REFERENCES `ADK_USER` (`ADK_USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_MESSAGE` (
  `ADK_MESSAGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADK_MESSAGE_FROM_USER_ID` int(11) NOT NULL,
  `ADK_MESSAGE_TO_USER_ID` int(11) NOT NULL,
  `ADK_MESSAGE_RESPOND_ID` int(11) DEFAULT NULL,
  `ADK_MESSAGE_TITLE` varchar(45) DEFAULT NULL,
  `ADK_MESSAGE_CONTENT` varchar(5000) DEFAULT NULL,
  `ADK_MESSAGE_DTE` datetime NOT NULL,
  `ADK_MESSAGE_READ` tinyint(1) NOT NULL DEFAULT '0',
  `ADK_MESSAGE_FROM_DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `ADK_MESSAGE_TO_DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `ADK_MESSAGE_DRAFT` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ADK_MESSAGE_ID`),
  UNIQUE KEY `ADK_MESSAGE_ID_UNIQUE` (`ADK_MESSAGE_ID`),
  KEY `ADK_MESSAGE_RESPOND_ID_idx` (`ADK_MESSAGE_RESPOND_ID`),
  CONSTRAINT `ADK_MESSAGE_RESPOND_ID` FOREIGN KEY (`ADK_MESSAGE_RESPOND_ID`) REFERENCES `ADK_MESSAGE` (`ADK_MESSAGE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=233 DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_MESSAGE_FILE_JCT` (
  `ADK_MESSAGE_ID` int(11) NOT NULL,
  `ADK_FILE_ID` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_PEAK` (
  `ADK_PEAK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADK_PEAK_NAME` varchar(40) NOT NULL,
  `ADK_PEAK_HEIGHT` int(11) NOT NULL,
  PRIMARY KEY (`ADK_PEAK_ID`),
  UNIQUE KEY `ADK_PEAK_ID_UNIQUE` (`ADK_PEAK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_USER` (
  `ADK_USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADK_USERGROUP_ID` int(11) NOT NULL,
  `ADK_USER_USERNAME` varchar(20) NOT NULL,
  `ADK_USER_PASSWORD` varchar(512) NOT NULL,
  `ADK_USER_NAME` varchar(40) NOT NULL,
  `ADK_USER_EMAIL` varchar(40) NOT NULL,
  PRIMARY KEY (`ADK_USER_ID`),
  UNIQUE KEY `ADK_USER_ID_UNIQUE` (`ADK_USER_ID`),
  UNIQUE KEY `ADK_USER_USERNAME_UNIQUE` (`ADK_USER_USERNAME`),
  KEY `ADK_USERGROUP_ID_idx` (`ADK_USERGROUP_ID`),
  CONSTRAINT `ADK_USERGROUP_ID` FOREIGN KEY (`ADK_USERGROUP_ID`) REFERENCES `ADK_USERGROUP` (`ADK_USERGROUP_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=110 DEFAULT CHARSET=latin1;

CREATE TABLE `ADK_USERGROUP` (
  `ADK_USERGROUP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADK_USERGROUP_CDE` varchar(3) NOT NULL,
  `ADK_USERGROUP_DESC` varchar(20) NOT NULL,
  PRIMARY KEY (`ADK_USERGROUP_ID`),
  UNIQUE KEY `ADK_USERGROUP_ID_UNIQUE` (`ADK_USERGROUP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;